# Configuração principal do Calamares
# liz — ISO Builder

# Sequência de módulos a executar durante a instalação
sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - networkcfg
    - hwclock
    - services-systemd
    - grubcfg
    - bootloader
    - packages
    - luksbootkeyfile
    - plymouthcfg
    - initramfscfg
    - initramfs
    - removeuser
    - umount
  - show:
    - finished

# Título da janela
branding: liz

# Permite que o usuário saia do instalador
prompt-install: true

# Interface gráfica: usa qt por padrão
interface: qt

# Log detalhado
debug: false
