# Calamares — Módulo partition
# Configuração de particionamento

---
efiSystemPartition:   "/boot/efi"
efiSystemPartitionSize: 300M
efiSystemPartitionName: "EFI System Partition"

userSwapChoices:
  - none
  - small
  - suspend
  - file

ensureSuspendToDisk: true
neverCreateSwap: false

defaultFileSystemType: "ext4"

availableFileSystemTypes:
  - "ext4"
  - "btrfs"
  - "xfs"
  - "f2fs"
