# Calamares — Módulo users
# Configuração de criação de usuário

---
defaultGroups:
  - name: users
    gid: 100
    system: true
    must_exist: false
  - sudo
  - audio
  - video
  - input
  - netdev

autologinGroup: autologin

sudoersGroup: sudo

setRootPassword: true

passwordRequirements:
  nonempty: true

allowWeakPasswords: false
allowPasswordSaves: false
